### ISSUE TITLE
Support for % (percentage)?

### ISSUE THREAD

**Issue by oliviermilla** [rubysolo/dentaku#11]
```
2.1.0 :008 > rate = "0.5% * ((x - 500000)/2500000)" 
2.1.0 :010 > Dentaku::Calculator.new.evaluate(rate, :x => 1)
RuntimeError: no rule matched [:numeric, :operator, :operator, :numeric]
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/dentaku-0.2.13/lib/dentaku/evaluator.rb:13:in `evaluate_token_stream'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/dentaku-0.2.13/lib/dentaku/evaluator.rb:7:in `evaluate'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/dentaku-0.2.13/lib/dentaku/calculator.rb:30:in `block in evaluate'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/dentaku-0.2.13/lib/dentaku/calculator.rb:50:in `store'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/dentaku-0.2.13/lib/dentaku/calculator.rb:28:in `evaluate'
from (irb):10
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
from /home/avril14th/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

**Comment by stoplion** [comment]
Does this still work?
`calculator.evaluate('56.47% + 15%')`
`NoMethodError: undefined method `dependencies' for nil:NilClass`
