### ISSUE TITLE
::ArgumentError when a function is used with bad arguments size

### ISSUE THREAD

**Issue by felgaete** [rubysolo/dentaku#176]
When you use a defined function with wrong arity Dentaku raises a `ArgumentError` instead of `Dentaku::ArgumentError`.
Is this the expected behavior?
Would it be better raise an error where we can identify the function been misused. I don't know if Dentaku::ArgumentError could do this

use case
```
Dentaku('IF(a, b)')
```
results
```
       13: from ...dentaku-3.3.0/lib/dentaku.rb:55:in `Dentaku'
       12: from ...dentaku-3.3.0/lib/dentaku.rb:11:in `evaluate'
       11: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:48:in `evaluate'
       10: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:58:in `evaluate!'
        9: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:127:in `store'
        8: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:60:in `block in evaluate!'
        7: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:86:in `ast'
        6: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:86:in `fetch'
        5: from ...dentaku-3.3.0/lib/dentaku/calculator.rb:94:in `block in ast'
        4: from ...dentaku-3.3.0/lib/dentaku/parser.rb:252:in `parse'
        3: from ...dentaku-3.3.0/lib/dentaku/parser.rb:48:in `consume'
        2: from ...dentaku-3.3.0/lib/dentaku/parser.rb:48:in `new'
        1: from ...dentaku-3.3.0/lib/dentaku/ast/functions/if.rb:8:in `initialize'
ArgumentError (wrong number of arguments (given 2, expected 3))

```

Thanks, great job with this lib btw!

**Comment by rubysolo** [comment]
Thanks for reporting!
