### ISSUE TITLE
NoMethorError when a comma is used

### ISSUE THREAD

**Issue by felgaete** [rubysolo/dentaku#177]
This cases
```
Dentaku(',')
Dentaku('a + b , c')
Dentaku('a,b')
```
raises a `NoMethodError` when parsed. It's the comma causing this.

```
       10: from ...dentaku-3.3.0/lib/dentaku.rb:55:in `Dentaku'
        9: ...dentaku-3.3.0/lib/dentaku.rb:11:in `evaluate'
        8: ...dentaku-3.3.0/lib/dentaku/calculator.rb:48:in `evaluate'
        7: ...dentaku-3.3.0/lib/dentaku/calculator.rb:58:in `evaluate!'
        6: ...dentaku-3.3.0/lib/dentaku/calculator.rb:127:in `store'
        5: ...dentaku-3.3.0/lib/dentaku/calculator.rb:60:in `block in evaluate!'
        4: ...dentaku-3.3.0/lib/dentaku/calculator.rb:86:in `ast'
        3: ...dentaku-3.3.0/lib/dentaku/calculator.rb:86:in `fetch'
        2: ...dentaku-3.3.0/lib/dentaku/calculator.rb:94:in `block in ast'
        1: ...dentaku-3.3.0/lib/dentaku/parser.rb:256:in `parse'
NoMethodError (undefined method `+' for nil:NilClass)

```

The expected result should be a `Dentaku::ParseError`

Thanks

**Comment by rubysolo** [comment]
Good catch, thanks!
