### ISSUE TITLE
some edge case statements does not return Dentaku error

### ISSUE THREAD

**Issue by a5-stable** [rubysolo/dentaku#277]
Greetings.
I know they rarely happen, but sometimes I want to deal with them.
these statements now return NoMethodError instead of Dentaku Error.

```
# Dentaku::Calculator.new.ast("()")
# parser.rb:41:in `consume': undefined method `peek' for nil:NilClass (NoMethodError)

# Dentaku::Calculator.new.ast("(})")
# parser.rb:44:in `consume': undefined method `min_param_count' for Dentaku::AST::Grouping:Class (NoMethodError)
```

**Comment by a5-stable** [comment]
try to fix it at #278.
