### ISSUE TITLE
Calculator.dependencies raises `undefined method `flat_map' for nil:NilClass` when the expression contains a call to (some?) included string functions

### ISSUE THREAD

**Issue by thomas-profitt** [rubysolo/dentaku#95]
Tested on commit 1b2036b

Example of failing unit tests:
```
    it "finds dependencies in a statement using CONCAT" do
      expect(calculator.dependencies("CONCAT(bob, dole)")).to eq(['bob', 'dole'])
    end

    it "finds dependencies in a statement using LEN" do
      expect(calculator.dependencies("LEN(bob)")).to eq(['bob'])
    end
```

Result, for both calls:
```
     NoMethodError:
       undefined method `flat_map' for nil:NilClass
     # ./lib/dentaku/ast/function.rb:11:in `dependencies'
     # ./lib/dentaku/calculator.rb:58:in `dependencies'
     # ./spec/calculator_spec.rb:70:in `block (3 levels) in <top (required)>'
```

**Comment by rubysolo** [comment]
Good catch, thanks!
